/* BuySooner Roadmap Page 10 renderer */
(function(){
function esc(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];});}
function css(){return `
.rm10-page{width:100%;max-width:1120px;min-height:1400px;margin:0 auto;padding:42px;position:relative;overflow:hidden;border-radius:28px;color:#1f2933;background:linear-gradient(135deg,#fff 0%,#f9fcfc 68%,#eef8f7 100%);box-shadow:0 30px 80px rgba(8,40,71,.18);font-family:Arial,Helvetica,sans-serif}
.rm10-topbar{display:flex;justify-content:space-between;align-items:flex-start;gap:24px;margin-bottom:26px}.rm10-brand-mark{width:68px;height:7px;border-radius:999px;background:#087a78;margin-bottom:8px}.rm10-logo{font-size:28px;line-height:1;letter-spacing:-.04em;color:#071f3a;font-weight:900}.rm10-tagline{margin-top:8px;color:#087a78;font-size:12px;font-weight:800}.rm10-page-label{min-width:245px;text-align:right;color:#071f3a;font-size:13px;font-weight:900}.rm10-progress{margin-top:9px;height:5px;background:rgba(8,40,71,.1);border-radius:999px;overflow:hidden}.rm10-progress span{display:block;width:71.4%;height:100%;background:#087a78}
.rm10-report{max-width:960px;margin:0 auto}.rm10-hero{margin:0 0 22px}.rm10-eyebrow{margin:0 0 9px;color:#087a78;font-size:12px;line-height:1;font-weight:900;text-transform:uppercase;letter-spacing:.16em}.rm10-hero h1{margin:0;color:#071f3a;font-size:clamp(44px,5.4vw,68px);line-height:.96;letter-spacing:-.06em;font-weight:900}.rm10-hero h1 span{color:#087a78}.rm10-hero p{margin:13px 0 0;color:#526071;font-size:17px;line-height:1.48;font-weight:700;max-width:790px}.rm10-context{display:flex;flex-wrap:wrap;gap:10px;margin-top:18px}.rm10-chip{display:inline-flex;align-items:center;gap:8px;padding:10px 14px;border-radius:999px;background:#fff;border:1px solid #d7e5e4;color:#071f3a;font-size:13px;line-height:1;font-weight:850;box-shadow:0 8px 20px rgba(12,51,88,.045)}.rm10-chip span{color:#087a78;font-weight:900}
.rm10-promise{margin:22px 0 24px;background:#f1fbfa;border:1px solid rgba(8,122,120,.24);border-radius:22px;padding:18px 20px;box-shadow:0 12px 28px rgba(12,51,88,.055)}.rm10-promise-head{display:flex;justify-content:space-between;gap:18px;align-items:center;margin-bottom:14px}.rm10-promise h2{margin:0;color:#071f3a;font-size:22px;line-height:1.05;font-weight:900;letter-spacing:-.03em}.rm10-promise p{margin:0;color:#526071;font-size:13.4px;line-height:1.36;font-weight:720}.rm10-promise-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.rm10-promise-item{display:grid;grid-template-columns:24px 1fr;gap:9px;align-items:start;background:#fff;border:1px solid rgba(8,122,120,.16);border-radius:16px;padding:13px 12px;color:#1f2933;font-size:13px;line-height:1.28;font-weight:800}.rm10-promise-tick{width:21px;height:21px;border-radius:999px;background:#087a78;color:#fff;display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:950;line-height:1}
.rm10-faq-panel{background:#fff;border:1px solid #d7e5e4;border-radius:24px;box-shadow:0 14px 34px rgba(12,51,88,.07);overflow:hidden}.rm10-faq-header{padding:22px 24px;border-bottom:1px solid #e4eeee;display:flex;justify-content:space-between;gap:20px;align-items:flex-end}.rm10-faq-header h2{margin:0;color:#071f3a;font-size:28px;line-height:1;font-weight:900;letter-spacing:-.04em}.rm10-faq-header p{margin:7px 0 0;color:#526071;font-size:14.4px;line-height:1.38;font-weight:720}.rm10-print-note{flex:0 0 auto;color:#087a78;font-size:12px;font-weight:850}.rm10-accordion{padding:8px 18px 18px}.rm10-acc{border-top:1px solid #e4eeee}.rm10-acc:first-child{border-top:0}.rm10-acc-btn{appearance:none;width:100%;border:0;background:transparent;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:18px 4px;cursor:pointer;text-align:left;color:#071f3a}.rm10-acc-title{display:flex;align-items:center;gap:12px}.rm10-acc-icon{width:34px;height:34px;border-radius:999px;background:#eaf6f5;color:#087a78;display:flex;align-items:center;justify-content:center;font-size:17px;font-weight:950}.rm10-acc-btn h3{margin:0;color:#071f3a;font-size:22px;line-height:1.08;font-weight:900;letter-spacing:-.03em}.rm10-acc-btn p{margin:4px 0 0;color:#526071;font-size:13.3px;line-height:1.3;font-weight:720}.rm10-chevron{width:34px;height:34px;border-radius:999px;border:1px solid rgba(8,122,120,.22);color:#087a78;display:flex;align-items:center;justify-content:center;font-size:20px;font-weight:900;transition:transform .25s ease,background .25s ease,color .25s ease}.rm10-acc.is-open .rm10-chevron{transform:rotate(45deg);background:#087a78;color:#fff}.rm10-acc-panel{display:none;padding:0 4px 20px}.rm10-acc.is-open .rm10-acc-panel{display:block}.rm10-qa-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.rm10-qa{background:#f9fcfc;border:1px solid #e4eeee;border-radius:16px;padding:16px 17px}.rm10-qa h4{margin:0 0 7px;color:#071f3a;font-size:15.8px;line-height:1.24;font-weight:900;letter-spacing:-.005em}.rm10-qa p{margin:0;color:#526071;font-size:13.8px;line-height:1.47;font-weight:700}.rm10-acc.is-open .rm10-qa{animation:rm10Fade .35s ease both}.rm10-acc.is-open .rm10-qa:nth-child(2){animation-delay:.04s}.rm10-acc.is-open .rm10-qa:nth-child(3){animation-delay:.08s}.rm10-acc.is-open .rm10-qa:nth-child(4){animation-delay:.12s}.rm10-acc.is-open .rm10-qa:nth-child(5){animation-delay:.16s}.rm10-acc.is-open .rm10-qa:nth-child(6){animation-delay:.2s}@keyframes rm10Fade{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}
.rm10-bottom{margin-top:22px;display:grid;grid-template-columns:1fr 1fr;gap:16px;align-items:stretch}.rm10-bottom-card{background:#fff;border:1px solid #d7e5e4;border-radius:20px;padding:22px 24px;box-shadow:0 12px 28px rgba(12,51,88,.055)}.rm10-bottom-card.primary{background:#f1fbfa;border-color:rgba(8,122,120,.24)}.rm10-bottom-card h2,.rm10-bottom-card h3{margin:0 0 9px;color:#071f3a;font-size:23px;line-height:1.08;font-weight:900;letter-spacing:-.035em}.rm10-bottom-card p{margin:0;color:#526071;font-size:14.2px;line-height:1.47;font-weight:720}.rm10-actions{display:flex;justify-content:space-between;gap:14px;margin-top:22px}.rm10-btn{appearance:none;border:0;border-radius:999px;padding:13px 21px;font-size:14px;font-weight:900;cursor:pointer}.rm10-back{background:#eaf6f5;color:#071f3a}.rm10-next{background:#087a78;color:#fff;box-shadow:0 10px 24px rgba(8,122,120,.2)}.rm10-footer{margin-top:18px;border-top:1px solid rgba(8,40,71,.09);padding-top:12px;color:#526071;font-size:10px;line-height:1.45;font-weight:650}.rm10-reveal{opacity:0;transform:translateY(18px);transition:opacity .55s ease,transform .55s ease}.rm10-reveal.is-visible{opacity:1;transform:translateY(0)}
@media(max-width:900px){.rm10-page{min-height:auto;padding:24px}.rm10-topbar,.rm10-promise-grid,.rm10-qa-grid,.rm10-bottom,.rm10-actions{display:grid;grid-template-columns:1fr}.rm10-page-label{text-align:left;min-width:0}.rm10-promise-head,.rm10-faq-header{display:block}.rm10-print-note{margin-top:8px}.rm10-btn{width:100%}}@media print{.rm10-page{max-width:none;min-height:100vh;box-shadow:none;border-radius:0}.rm10-actions{display:none}.rm10-acc-panel{display:block!important}.rm10-chevron{display:none}.rm10-reveal{opacity:1!important;transform:none!important}.rm10-qa{break-inside:avoid}.rm10-faq-panel,.rm10-bottom-card,.rm10-promise{box-shadow:none}}
`;}
function reveal(root){var els=Array.prototype.slice.call(root.querySelectorAll('.rm10-reveal'));els.forEach(function(el,i){el.style.transitionDelay=(i*70)+'ms';});if(!('IntersectionObserver' in window)){els.forEach(function(el){el.classList.add('is-visible');});return;}var io=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('is-visible');io.unobserve(entry.target);}});},{threshold:.14});els.forEach(function(el){io.observe(el);});}
function goToPage11(d,root){
  function render(){window.renderRoadmapPage11(d,root);window.scrollTo({top:0,behavior:'smooth'});}
  if(window.renderRoadmapPage11){render();return;}
  var existing=document.querySelector('script[data-roadmap-page11="true"]');
  if(existing){existing.addEventListener('load',function(){if(window.renderRoadmapPage11){render();}});return;}
  var script=document.createElement('script');
  script.src='roadmap-page11.js?v=20260518-24';
  script.dataset.roadmapPage11='true';
  script.onload=function(){if(window.renderRoadmapPage11){render();}else{alert('Page 11 could not load. Refresh the roadmap and try again.');}};
  script.onerror=function(){alert('Page 11 could not load. Refresh the roadmap and try again.');};
  document.body.appendChild(script);
}
function renderRoadmapPage10(data,root){
var d=data||{},c=d.customer||{},p=d.property||{};
var customerName=String(c.name||c.fullName||'Customer').trim()||'Customer';
var address=String(p.address||p.suburb||'your target home').trim()||'your target home';
var styleId='roadmap-page10-style';if(!document.getElementById(styleId)){var s=document.createElement('style');s.id=styleId;s.textContent=css();document.head.appendChild(s);}
var groups=[
{key:'money',icon:'$',title:'Money & Costs',sub:'What you pay, what you do not pay, and what still needs to be assessed.',items:[
['Do I pay BuySooner each month?','No. You make your normal mortgage repayments to the bank. You do not make monthly payments to BuySooner.'],
['Does BuySooner charge interest?','No. There is no interest and no compounding BuySooner balance.'],
['How much can BuySooner contribute?','Usually around 10% of the purchase price, subject to assessment and approval. For some structures, lower or higher contributions may be assessed.'],
['How much do I need to contribute?','The standard position is 10%, from verified savings or other approved sources. Your final contribution is confirmed during assessment.'],
['Could BuySooner help me avoid LMI?','Potentially, depending on lender approval, valuation, loan structure and deposit position.'],
['What costs do I still pay?','Usual home purchase costs may apply, including stamp duty, conveyancing, inspections, lender costs, valuation and insurance.']
]},
{key:'ownership',icon:'⌂',title:'Ownership & Control',sub:'How ownership works while BuySooner is helping bridge the gap.',items:[
['Do I own the home from Day 1?','Yes. You are the registered owner from settlement. BuySooner provides the bridge capital and holds agreed rights to be paid out at exit.'],
['Can I renovate or improve the property?','Generally, yes, but major changes may require lender approval and must remain consistent with the BuySooner terms.'],
['Can I sell the home?','Yes. A sale can be an exit pathway. BuySooner is repaid from sale proceeds according to the agreed terms.'],
['Can I refinance early?','Yes. If a lender approves the refinance and the BuySooner payout can be met, BuySooner can step out earlier.']
]},
{key:'exit',icon:'→',title:'Exit & Life Changes',sub:'What happens at refinance, sale, review points or if life changes.',items:[
['When does BuySooner get paid?','At refinance, sale or another approved exit. BuySooner receives the original bridge plus the agreed exit amount.'],
['Who sets the property value?','The value is set through the agreed valuation or sale process under the BuySooner terms.'],
['What if I am not ready after 3 to 5 years?','The pathway is reviewed. BuySooner is designed to be temporary, but the review considers valuation, lender approval and serviceability.'],
['Can I buy BuySooner out?','Yes. You can buy out BuySooner through refinance, sale or another approved pathway once the numbers align.'],
['What if the property value goes down?','The BuySooner outcome depends on the actual exit value. Property growth is illustrative and not guaranteed.'],
['What about life changes?','Life events may require lender approval, serviceability review, valuation updates and refinance readiness assessment.']
]}
];
function groupMarkup(g,i){return `<article class="rm10-acc ${i===0?'is-open':''}" data-rm10-acc="${esc(g.key)}"><button class="rm10-acc-btn" type="button" aria-expanded="${i===0?'true':'false'}"><span class="rm10-acc-title"><span class="rm10-acc-icon">${esc(g.icon)}</span><span><h3>${esc(g.title)}</h3><p>${esc(g.sub)}</p></span></span><span class="rm10-chevron">+</span></button><div class="rm10-acc-panel"><div class="rm10-qa-grid">${g.items.map(function(item){return `<div class="rm10-qa"><h4>${esc(item[0])}</h4><p>${esc(item[1])}</p></div>`;}).join('')}</div></div></article>`;}
root.innerHTML=`<section class="rm10-page"><header class="rm10-topbar"><div><div class="rm10-brand-mark"></div><div class="rm10-logo">BuySooner</div><div class="rm10-tagline">Buy sooner. Buy smarter.</div></div><div class="rm10-page-label">Page 10 - Customer FAQ<div class="rm10-progress"><span></span></div></div></header><div class="rm10-report"><section class="rm10-hero rm10-reveal"><p class="rm10-eyebrow">Customer FAQ</p><h1>Clear answers before <span>you move forward.</span></h1><p>${esc(customerName)}, these questions explain how BuySooner works in plain English before you continue through your Roadmap.</p><div class="rm10-context"><div class="rm10-chip"><span>Customer</span> ${esc(customerName)}</div><div class="rm10-chip"><span>Roadmap</span> ${esc(address)}</div></div></section><section class="rm10-promise rm10-reveal"><div class="rm10-promise-head"><h2>Our promise</h2><p>Simple structure. Clear terms. No monthly BuySooner bill.</p></div><div class="rm10-promise-grid"><div class="rm10-promise-item"><span class="rm10-promise-tick">✓</span><span>No monthly payments to BuySooner.</span></div><div class="rm10-promise-item"><span class="rm10-promise-tick">✓</span><span>No interest or compounding BuySooner balance.</span></div><div class="rm10-promise-item"><span class="rm10-promise-tick">✓</span><span>Clear terms from Day 1.</span></div><div class="rm10-promise-item"><span class="rm10-promise-tick">✓</span><span>BuySooner is paid at exit.</span></div></div></section><section class="rm10-faq-panel rm10-reveal"><div class="rm10-faq-header"><div><h2>Your key questions</h2><p>Open each section to review the answers. The full FAQ appears when printed or saved as PDF.</p></div><div class="rm10-print-note">Print-safe FAQ</div></div><div class="rm10-accordion">${groups.map(groupMarkup).join('')}</div></section><section class="rm10-bottom rm10-reveal"><div class="rm10-bottom-card primary"><h2>BuySooner helps bridge the gap, not take over your home.</h2><p>The aim is to help you enter the market sooner, build equity sooner and move toward a standard mortgage when the numbers are ready.</p></div><aside class="rm10-bottom-card"><h3>Plain-English reminder</h3><p>This FAQ is explanatory only. The final terms, costs and obligations are set out in the formal BuySooner documents and lender documents.</p></aside></section><div class="rm10-actions rm10-reveal"><button id="rm10BackPage9" class="rm10-btn rm10-back" type="button">Back</button><button id="rm10NextPage11" class="rm10-btn rm10-next" type="button">Next: Support Pathway &#8594;</button></div><footer class="rm10-footer">Prepared for ${esc(customerName)}. This Roadmap is an indicative illustration only. It is not approval, financial advice, a valuation, or a credit offer. Final outcomes depend on assessment, valuation, lender approval, legal documents and BuySooner approval.</footer></div></section>`;
Array.prototype.slice.call(root.querySelectorAll('.rm10-acc')).forEach(function(acc){var btn=acc.querySelector('.rm10-acc-btn');if(btn){btn.addEventListener('click',function(){var isOpen=acc.classList.contains('is-open');Array.prototype.slice.call(root.querySelectorAll('.rm10-acc')).forEach(function(other){other.classList.remove('is-open');var otherBtn=other.querySelector('.rm10-acc-btn');if(otherBtn){otherBtn.setAttribute('aria-expanded','false');}});if(!isOpen){acc.classList.add('is-open');btn.setAttribute('aria-expanded','true');}});}});
reveal(root);
var back=root.querySelector('#rm10BackPage9');if(back){back.addEventListener('click',function(){if(window.renderRoadmapPage9){window.renderRoadmapPage9(d,root);window.scrollTo({top:0,behavior:'smooth'});}});}
var next=root.querySelector('#rm10NextPage11');if(next){next.addEventListener('click',function(){goToPage11(d,root);});}
}
window.renderRoadmapPage10=renderRoadmapPage10;
})();
