/* BuySooner Roadmap Page 3 renderer */
(function(){
function esc(v){return String(v==null?'':v).replace(/[&<>'\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c];});}
function num(v){if(typeof v==='number')return Number.isFinite(v)?v:0;var n=Number(String(v==null?'':v).replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0;}
function money(v){return window.BSRoadmap&&BSRoadmap.money?BSRoadmap.money(v):new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(num(v));}
function css(){return `
.rm3-page{width:100%;max-width:1120px;min-height:1400px;margin:0 auto;padding:42px;position:relative;overflow:hidden;border-radius:28px;color:#1f2933;background:radial-gradient(circle at 82% 12%,rgba(8,122,120,.13),transparent 31%),linear-gradient(135deg,#fff 0%,#f7fbfb 72%,#e9f6f3 100%);box-shadow:0 30px 80px rgba(8,40,71,.18)}
.rm3-topbar{display:flex;justify-content:space-between;align-items:flex-start;gap:24px;margin-bottom:38px}.rm3-brand-mark{width:68px;height:7px;border-radius:999px;background:#087a78;margin-bottom:8px}.rm3-logo{font-size:28px;line-height:1;letter-spacing:-.05em;color:#071f3a;font-weight:900}.rm3-tagline{margin-top:8px;color:#087a78;font-size:12px;font-weight:800}.rm3-page-label{min-width:245px;text-align:right;color:#071f3a;font-size:13px;font-weight:900}.rm3-progress{margin-top:9px;height:5px;background:rgba(8,40,71,.1);border-radius:999px;overflow:hidden}.rm3-progress span{display:block;width:21.42%;height:100%;background:#087a78}
.rm3-hero{display:grid;grid-template-columns:1.14fr .86fr;gap:32px;align-items:center;margin-bottom:26px}.rm3-eyebrow{margin:0 0 8px;color:#087a78;font-size:12px;font-weight:950;text-transform:uppercase;letter-spacing:.08em}.rm3-hero h1{margin:0;color:#071f3a;font-size:clamp(42px,5.4vw,64px);line-height:.98;letter-spacing:-.065em;font-weight:950}.rm3-hero h2{margin:16px 0 0;color:#071f3a;font-size:23px;line-height:1.18;letter-spacing:-.035em;font-weight:900}.rm3-hero h2 span{color:#087a78}.rm3-image-card{aspect-ratio:1.22/1;min-height:240px;border-radius:26px;overflow:hidden;background:#eef6f5;box-shadow:0 10px 26px rgba(12,51,88,.08)}.rm3-image-card img{width:100%;height:100%;display:block;object-fit:cover}
.rm3-card{background:rgba(255,255,255,.94);border:1px solid rgba(215,229,228,.75);border-radius:20px;box-shadow:0 10px 26px rgba(12,51,88,.08)}.rm3-strip{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:24px}.rm3-metric{padding:18px 16px;border-radius:18px;background:#fff;border:1px solid #d7e5e4;text-align:center;min-height:128px;display:flex;flex-direction:column;justify-content:center}.rm3-metric.highlight{background:#eaf6f5;border-color:rgba(8,122,120,.24)}.rm3-metric-label{color:#64748b;font-size:11px;font-weight:950;text-transform:uppercase;letter-spacing:.07em;margin-bottom:9px}.rm3-metric-value{color:#071f3a;font-size:24px;line-height:1.1;letter-spacing:-.035em;font-weight:950}.rm3-metric.highlight .rm3-metric-value{color:#087a78}.rm3-metric-sub{margin-top:8px;color:#64748b;font-size:12px;line-height:1.3;font-weight:800}
.rm3-reality{padding:30px;margin-bottom:24px}.rm3-reality h2,.rm3-summary h2{margin:0 0 20px;color:#071f3a;font-size:28px;line-height:1.08;letter-spacing:-.04em;font-weight:950}.rm3-blocks{display:grid;grid-template-columns:1fr 1fr;gap:18px}.rm3-block{padding:20px;border-radius:18px;background:#f7fbfb;border:1px solid #d7e5e4}.rm3-block h3{margin:0 0 8px;color:#087a78;font-size:18px;line-height:1.15;font-weight:950;letter-spacing:-.025em}.rm3-block p{margin:0;color:#526071;font-size:16px;line-height:1.5;font-weight:720}.rm3-summary{padding:28px;margin-bottom:22px;background:#eaf6f5;border-color:rgba(8,122,120,.2);text-align:center}.rm3-summary h2{margin-bottom:10px}.rm3-summary p{margin:0 auto;max-width:850px;color:#056261;font-size:20px;line-height:1.45;font-weight:900}.rm3-next-wrap{display:flex;justify-content:flex-end}.rm3-next-btn{appearance:none;border:0;border-radius:999px;background:#087a78;color:#fff;padding:15px 24px;font-size:15px;font-weight:900;cursor:pointer;box-shadow:0 10px 24px rgba(8,122,120,.22)}.rm3-next-btn:hover{background:#056261}.rm3-footer{margin-top:24px;border-top:1px solid rgba(8,40,71,.09);padding-top:12px;color:#526071;font-size:10px;line-height:1.45;font-weight:650}
@media(max-width:900px){.rm3-page{min-height:auto;padding:24px}.rm3-topbar,.rm3-hero,.rm3-strip,.rm3-blocks{display:grid;grid-template-columns:1fr}.rm3-page-label{text-align:left;min-width:0}.rm3-next-wrap{justify-content:stretch}.rm3-next-btn{width:100%}}@media print{.rm3-page{max-width:none;min-height:100vh;box-shadow:none;border-radius:0}}`;}
function renderRoadmapPage3(data,root){
var d=data||{},c=d.customer||{},p=d.property||{},f=d.finance||{},a=d.assumptions||{},der=d.derived||{},fmt=der.formatted||{};
var customerName=String(c.name||'Customer').trim()||'Customer';
var address=String(p.address||'').trim();
var suburb=String(p.suburb||'').trim();
var targetProperty=address||suburb||'your target property';
if(address&&suburb&&address.toLowerCase().indexOf(suburb.toLowerCase())===-1){targetProperty=address+', '+suburb;}
var price=num(p.targetPurchasePrice);
var contribution=num(f.customerContribution);
var boost=num(f.buySoonerBoost||der.buySoonerBoost);
var totalDeposit=num(der.totalDeposit)||(contribution+boost);
var bankLoan=num(f.estimatedBankLoan||der.estimatedBankLoan)||(price?Math.max(0,price-totalDeposit):0);
var startYear=a.refinanceStartYear||3;
var endYear=a.refinanceEndYear||5;
var styleId='roadmap-page3-style';if(!document.getElementById(styleId)){var s=document.createElement('style');s.id=styleId;s.textContent=css();document.head.appendChild(s);}
root.innerHTML=`<section class="rm3-page"><header class="rm3-topbar"><div><div class="rm3-brand-mark"></div><div class="rm3-logo">BuySooner</div><div class="rm3-tagline">Buy sooner. Buy smarter.</div></div><div class="rm3-page-label">Page 3 - Your Deposit Bridge<div class="rm3-progress"><span></span></div></div></header><section class="rm3-hero"><div><p class="rm3-eyebrow">Deposit Bridge</p><h1>Your Deposit Bridge</h1><h2><span>${esc(targetProperty)}</span> — you own the home from day one.</h2></div><aside class="rm3-image-card"><img src="j3.jpg" alt="Deposit bridge and home ownership" onerror="this.onerror=null;this.src='p3.jpg';"></aside></section><section class="rm3-strip"><div class="rm3-metric"><div class="rm3-metric-label">Title</div><div class="rm3-metric-value">You own the home</div><div class="rm3-metric-sub">From Day 1</div></div><div class="rm3-metric"><div class="rm3-metric-label">Bank loan</div><div class="rm3-metric-value">${fmt.estimatedBankLoan||money(bankLoan)}</div><div class="rm3-metric-sub">Standard mortgage structure</div></div><div class="rm3-metric highlight"><div class="rm3-metric-label">BuySooner Boost</div><div class="rm3-metric-value">${fmt.buySoonerBoost||money(boost)}</div><div class="rm3-metric-sub">Deposit gap bridge</div></div><div class="rm3-metric"><div class="rm3-metric-label">BuySooner payments</div><div class="rm3-metric-value">$0 monthly</div><div class="rm3-metric-sub">No monthly payments to BuySooner</div></div></section><section class="rm3-card rm3-reality"><h2>The practical reality</h2><div class="rm3-blocks"><article class="rm3-block"><h3>The problem</h3><p>You have enough momentum to buy, but not enough deposit to reach the structure the bank wants.</p></article><article class="rm3-block"><h3>The reality</h3><p>BuySooner bridges the deposit gap so you can buy the home now, with your name on title from day one.</p></article><article class="rm3-block"><h3>The structure</h3><p>Your bank loan does the heavy lifting. BuySooner sits beside it as the deposit bridge, with $0 monthly payments to BuySooner.</p></article><article class="rm3-block"><h3>The pathway</h3><p>The aim is to build equity, reduce the gap, and refinance into a standard bank mortgage when the numbers work. Target refinance window is Year ${esc(startYear)} to Year ${esc(endYear)}.</p></article></div></section><section class="rm3-card rm3-summary"><h2>What this means for ${esc(customerName)}</h2><p>BuySooner is designed to turn a deposit shortfall into a clear ownership pathway — buy now, build equity, and refinance when the numbers work.</p></section><div class="rm3-next-wrap"><button id="rm3NextPage4" class="rm3-next-btn" type="button">Next: See Your Path to 100% Ownership &#8594;</button></div><footer class="rm3-footer">Prepared for ${esc(customerName)}. This Roadmap is an indicative illustration only. It is not approval, financial advice, a valuation, or a credit offer.</footer></section>`;
var next=root.querySelector('#rm3NextPage4');if(next){next.addEventListener('click',function(){if(window.renderRoadmapPage4){window.renderRoadmapPage4(d,root);}else{alert('Page 4 is next: See Your Path to 100% Ownership.');}});}
}
window.renderRoadmapPage3=renderRoadmapPage3;
})();
