/* BuySooner Roadmap Page 6 renderer */
(function(){
function esc(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];});}
function css(){return `
.rm6-page{width:100%;max-width:1120px;min-height:1400px;margin:0 auto;padding:42px;position:relative;overflow:hidden;border-radius:28px;color:#1f2933;background:linear-gradient(135deg,#fff 0%,#f9fcfc 70%,#eef8f7 100%);box-shadow:0 30px 80px rgba(8,40,71,.18)}
.rm6-topbar{display:flex;justify-content:space-between;align-items:flex-start;gap:24px;margin-bottom:26px}.rm6-brand-mark{width:68px;height:7px;border-radius:999px;background:#087a78;margin-bottom:8px}.rm6-logo{font-size:28px;line-height:1;letter-spacing:-.05em;color:#071f3a;font-weight:900}.rm6-tagline{margin-top:8px;color:#087a78;font-size:12px;font-weight:800}.rm6-page-label{min-width:245px;text-align:right;color:#071f3a;font-size:13px;font-weight:900}.rm6-progress{margin-top:9px;height:5px;background:rgba(8,40,71,.1);border-radius:999px;overflow:hidden}.rm6-progress span{display:block;width:42.84%;height:100%;background:#087a78}
.rm6-report{max-width:960px;margin:0 auto}.rm6-hero{display:grid;grid-template-columns:1.13fr .87fr;gap:26px;align-items:center;margin-bottom:24px}.rm6-hero h1{margin:0;color:#071f3a;font-size:clamp(48px,6.3vw,76px);line-height:.92;letter-spacing:-.07em;font-weight:950}.rm6-hero h1 span{color:#087a78}.rm6-hero-rule{width:96px;height:4px;border-radius:999px;background:#d9aa2d;margin:14px 0 0}.rm6-hero p{margin:14px 0 0;color:#071f3a;font-size:18px;line-height:1.34;font-weight:780;max-width:610px}.rm6-image-card{height:265px;border-radius:22px;overflow:hidden;background:#eef6f5;border:1px solid #d7e5e4;box-shadow:0 10px 26px rgba(12,51,88,.08)}.rm6-image-card img{width:100%;height:100%;display:block;object-fit:cover}
.rm6-map-intro{margin:0 0 18px;text-align:center}.rm6-map-intro h2{margin:0;color:#071f3a;font-size:30px;line-height:1.06;letter-spacing:-.045em;font-weight:950}.rm6-map-intro h2 span{color:#087a78}.rm6-map-intro p{margin:8px auto 0;max-width:690px;color:#526071;font-size:15.5px;line-height:1.42;font-weight:760}.rm6-accordion{position:relative;margin:0 auto 22px;padding-left:28px}.rm6-accordion:before{content:"";position:absolute;left:11px;top:18px;bottom:18px;width:3px;border-radius:999px;background:linear-gradient(180deg,#087a78,#d7e5e4)}.rm6-item{position:relative;margin:0 0 13px}.rm6-item:before{content:"";position:absolute;left:-24px;top:22px;width:13px;height:13px;border-radius:999px;background:#087a78;border:4px solid #eaf6f5;box-shadow:0 0 0 1px rgba(8,122,120,.25)}.rm6-step-btn{width:100%;appearance:none;border:1px solid #d7e5e4;border-radius:18px;background:#fff;color:#071f3a;padding:18px 22px;text-align:left;display:grid;grid-template-columns:1fr auto;gap:16px;align-items:center;cursor:pointer;box-shadow:0 10px 24px rgba(12,51,88,.06)}.rm6-step-title{display:flex;gap:16px;align-items:baseline}.rm6-step-num{color:#087a78;font-size:15px;font-weight:950;letter-spacing:.05em}.rm6-step-heading{font-size:23px;line-height:1.05;letter-spacing:-.035em;font-weight:950}.rm6-step-prompt{display:block;margin-top:5px;color:#526071;font-size:13.5px;font-weight:800}.rm6-step-icon{width:34px;height:34px;border-radius:999px;background:#eaf6f5;color:#087a78;display:flex;align-items:center;justify-content:center;font-size:21px;font-weight:950;transition:transform .24s ease}.rm6-panel{display:none;border:1px solid #d7e5e4;border-top:0;border-radius:0 0 18px 18px;background:#f7fbfb;margin:-8px 0 0;padding:22px 26px 23px;box-shadow:0 12px 24px rgba(12,51,88,.05)}.rm6-panel p{margin:0;color:#1f2933;font-size:16.5px;line-height:1.5;font-weight:730}.rm6-item.is-open .rm6-step-btn{border-color:rgba(8,122,120,.32);background:linear-gradient(135deg,#fff 0%,#f1fbfa 100%)}.rm6-item.is-open .rm6-step-icon{transform:rotate(45deg);background:#087a78;color:#fff}.rm6-item.is-open .rm6-panel{display:block;animation:rm6Open .28s ease both}@keyframes rm6Open{from{opacity:0;transform:translateY(-8px)}to{opacity:1;transform:translateY(0)}}
.rm6-bottom{display:grid;grid-template-columns:280px 1fr;gap:0;align-items:stretch;margin-top:18px;padding:0;border:1px solid rgba(8,122,120,.26);border-radius:18px;background:#f2fbfa;box-shadow:0 12px 28px rgba(12,51,88,.06);overflow:hidden}.rm6-bottom-title{display:flex;align-items:center;border-right:1px solid #d7e5e4;padding:22px 24px}.rm6-bottom-title h2{margin:0;color:#071f3a;font-size:26px;line-height:1.02;letter-spacing:-.045em;font-weight:950}.rm6-bottom-title span{display:block;width:54px;height:3px;border-radius:999px;background:#d9aa2d;margin-top:10px}.rm6-bottom-copy{padding:23px 28px;display:flex;align-items:center}.rm6-bottom-copy p{margin:0;color:#1f2933;font-size:17px;line-height:1.42;font-weight:760}.rm6-bottom-copy strong{display:block;margin-top:3px;color:#087a78;font-weight:950}.rm6-actions{display:flex;justify-content:space-between;gap:14px;margin-top:20px}.rm6-btn{appearance:none;border:0;border-radius:999px;padding:13px 21px;font-size:14px;font-weight:900;cursor:pointer}.rm6-back{background:#eaf6f5;color:#071f3a}.rm6-next{background:#087a78;color:#fff;box-shadow:0 10px 24px rgba(8,122,120,.2)}.rm6-footer{margin-top:18px;border-top:1px solid rgba(8,40,71,.09);padding-top:12px;color:#526071;font-size:10px;line-height:1.45;font-weight:650}.rm6-reveal{opacity:0;transform:translateY(18px);transition:opacity .55s ease,transform .55s ease}.rm6-reveal.is-visible{opacity:1;transform:translateY(0)}
@media(max-width:900px){.rm6-page{min-height:auto;padding:24px}.rm6-topbar,.rm6-hero,.rm6-bottom,.rm6-actions{display:grid;grid-template-columns:1fr}.rm6-page-label{text-align:left;min-width:0}.rm6-image-card{height:225px}.rm6-accordion{padding-left:22px}.rm6-step-title{display:block}.rm6-step-heading{display:block;margin-top:3px}.rm6-bottom-title{border-right:0;border-bottom:1px solid #d7e5e4}.rm6-bottom-copy{padding:22px 20px}.rm6-btn{width:100%}}@media print{.rm6-page{max-width:none;min-height:100vh;box-shadow:none;border-radius:0}.rm6-actions{display:none}.rm6-panel{display:block!important}.rm6-step-icon{display:none}.rm6-reveal{opacity:1!important;transform:none!important}}`;}
function revealPage6(root){var els=Array.prototype.slice.call(root.querySelectorAll('.rm6-reveal'));els.forEach(function(el,i){el.style.transitionDelay=(i*70)+'ms';});if(!('IntersectionObserver' in window)){els.forEach(function(el){el.classList.add('is-visible');});return;}var io=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('is-visible');io.unobserve(entry.target);}});},{threshold:0.16});els.forEach(function(el){io.observe(el);});}
function goToPage7(d,root){
  function render(){window.renderRoadmapPage7(d,root);window.scrollTo({top:0,behavior:'smooth'});}
  if(window.renderRoadmapPage7){render();return;}
  var existing=document.querySelector('script[data-roadmap-page7="true"]');
  if(existing){existing.addEventListener('load',function(){if(window.renderRoadmapPage7){render();}});return;}
  var script=document.createElement('script');
  script.src='roadmap-page7.js?v=20260518-20';
  script.dataset.roadmapPage7='true';
  script.onload=function(){if(window.renderRoadmapPage7){render();}else{alert('Page 7 could not load. Refresh the roadmap and try again.');}};
  script.onerror=function(){alert('Page 7 could not load. Refresh the roadmap and try again.');};
  document.body.appendChild(script);
}
function renderRoadmapPage6(data,root){
var d=data||{},c=d.customer||{};
var customerName=String(c.name||'Customer').trim()||'Customer';
var styleId='roadmap-page6-style';if(!document.getElementById(styleId)){var s=document.createElement('style');s.id=styleId;s.textContent=css();document.head.appendChild(s);}
var steps=[
{n:'01',h:'Day 1: Move In',prompt:'See what happens',body:'You provide your deposit; BuySooner bridges the gap. You unlock the keys and start building equity in your own four walls from the very first day.'},
{n:'02',h:'Years 1–2: Momentum',prompt:'See what builds',body:'As you pay down your mortgage and the market moves, your ownership stake grows. You are no longer paying a landlord — you are investing in yourself.'},
{n:'03',h:'Year 3: The Checkpoint',prompt:'See what we review',body:'We sit down together to review your progress. If your equity has grown and the numbers align, we begin the transition to your long-term bank.'},
{n:'04',h:'Years 3–5: The Exit Window',prompt:'See how BuySooner steps out',body:'This is the refinance sweet spot. When the time is right, you switch to a standard bank mortgage and BuySooner steps out of the picture entirely.'},
{n:'05',h:'The Result: Total Freedom',prompt:'See where this leads',body:'BuySooner is repaid in full. You are left with a standard mortgage, a wealth of equity, and a home that is 100% yours.'}
];
function stepHtml(step,i){return '<article class="rm6-item rm6-reveal '+(i===0?'is-open':'')+'"><button class="rm6-step-btn" type="button" aria-expanded="'+(i===0?'true':'false')+'"><span><span class="rm6-step-title"><span class="rm6-step-num">'+step.n+'</span><span class="rm6-step-heading">'+esc(step.h)+'</span></span><span class="rm6-step-prompt">'+esc(step.prompt)+'</span></span><span class="rm6-step-icon">+</span></button><div class="rm6-panel"><p>'+esc(step.body)+'</p></div></article>';}
root.innerHTML=`<section class="rm6-page"><header class="rm6-topbar"><div><div class="rm6-brand-mark"></div><div class="rm6-logo">BuySooner</div><div class="rm6-tagline">Buy sooner. Buy smarter.</div></div><div class="rm6-page-label">Page 6 - Path to 100% Ownership<div class="rm6-progress"><span></span></div></div></header><div class="rm6-report"><section class="rm6-hero rm6-reveal"><div><h1>Your Path to <span>100% Ownership</span></h1><div class="rm6-hero-rule"></div><p>BuySooner is your head start — designed to help you step in today and step up tomorrow.</p></div><aside class="rm6-image-card"><img src="p11.jpg" alt="Home ownership with BuySooner" onerror="this.style.visibility='hidden';"></aside></section><section class="rm6-map-intro rm6-reveal"><h2>Let’s map this out together, <span>${esc(customerName)}.</span></h2><p>Click each step to see how the pathway works from move-in to full independence.</p></section><section class="rm6-accordion" aria-label="Path to 100 percent ownership">${steps.map(stepHtml).join('')}</section><section class="rm6-bottom rm6-reveal"><div class="rm6-bottom-title"><h2>The Bottom<br>Line<span></span></h2></div><div class="rm6-bottom-copy"><p>Stop waiting for the perfect market. Build equity while others keep saving for a deposit.<strong>Our goal is not to stay in your home — it is to help you get into it sooner, then step out when the numbers work.</strong></p></div></section><div class="rm6-actions rm6-reveal"><button id="rm6BackPage5" class="rm6-btn rm6-back" type="button">Back</button><button id="rm6NextPage7" class="rm6-btn rm6-next" type="button">Next: How the Numbers Work &rarr;</button></div><footer class="rm6-footer">Prepared for ${esc(customerName)}. This Roadmap is an indicative illustration only. It is not approval, financial advice, a valuation, or a credit offer.</footer></div></section>`;
revealPage6(root);
Array.prototype.slice.call(root.querySelectorAll('.rm6-item')).forEach(function(item){var btn=item.querySelector('.rm6-step-btn');btn.addEventListener('click',function(){Array.prototype.slice.call(root.querySelectorAll('.rm6-item')).forEach(function(other){if(other!==item){other.classList.remove('is-open');var ob=other.querySelector('.rm6-step-btn');if(ob)ob.setAttribute('aria-expanded','false');}});var open=!item.classList.contains('is-open');item.classList.toggle('is-open',open);btn.setAttribute('aria-expanded',open?'true':'false');});});
var back=root.querySelector('#rm6BackPage5');if(back){back.addEventListener('click',function(){if(window.renderRoadmapPage5){window.renderRoadmapPage5(d,root);window.scrollTo({top:0,behavior:'smooth'});}});}
var next=root.querySelector('#rm6NextPage7');if(next){next.addEventListener('click',function(){goToPage7(d,root);});}
}
window.renderRoadmapPage6=renderRoadmapPage6;
})();
